# Generated by Django 4.2.7 on 2024-02-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='addres',
            name='fname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='addres',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
