# Generated by Django 4.2.7 on 2024-02-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_addres_fname_addres_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addres',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
