# Generated by Django 4.2.7 on 2024-02-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='style',
        ),
    ]
